### ISSUE TITLE
Detect if mouse is at the edge or outside of the game window (such as on the top window bar) and force show mouse

### ISSUE THREAD

**Issue by subsoap** [subsoap/defos#31] opened 2017-11-08 02:58 UTC
It's too hard to scale / move window otherwise

**Comment by chaosddp** [comment] 2017-11-08 07:33
Then we have to provide a update function so that we are enble to do check.
How about provide a method like is_mouse_exiting to developer, so that we can determine if they need to show the cursor or not by calling existing method.

**Comment by subsoap** [comment] 2017-11-08 14:30
That's a good idea **is_cursor_within_window** maybe?

**Comment by subsoap** [comment] 2017-11-08 23:12
I started Window support here

https://github.com/subsoap/defos/tree/is_mouse_cursor_within_window

@chaosddp could you test this?

@AGulev could you add Mac support? Is Mac support needed? It is on Windows because the cursor will hide still if the mouse is on the title/edges which makes resizing a pain.

**Comment by chaosddp** [comment] 2017-11-09 09:55
@subsoap I've tested on my Windows 10.
1. the detect bound should exclude the titlebar, it seems like 32 pixel high?
2. When i trying to move the cursor into the window, it was disappeared near the edge, but not exactly on the edge(red rectangle  in following image), so still cannot resize the window easily. Maybe caused by window shadow effect?
How about add a buffer to the detect bound, or make it as  parameter to set the bound?

![issue31](https://user-images.githubusercontent.com/1094273/32599113-7bf09678-c576-11e7-8fef-dd9445bda2a3.png)

**Comment by subsoap** [comment] 2017-11-09 15:51
@chaosddp If you move your mouse around inside the window does it consistently say it's within the client window or does it sometimes say it's outside of the client window sometimes even while inside?

**Comment by AGulev** [comment] 2017-11-09 17:36
Hard week, I'll back to this issue after next week

**Comment by chaosddp** [comment] 2017-11-10 02:00
@subsoap only near the edge in the window, it will switch between in/outside for several time, then it will be stable if i do not move the mouse

**Comment by subsoap** [comment] 2017-11-10 03:20
@chaosddp I think there may be a better approach that's possible for detecting mouse within client window with what we have available. I'll need to do some more reading and testing.

**Comment by subsoap** [comment] 2017-12-01 23:23
@chaosddp I don't have progress on this yet, any ideas?

**Comment by chaosddp** [comment] 2017-12-04 01:48
@subsoap sorry so late, how about SetWindowLongPtr  to hook the mouse in/out event, i have not try this on defold game yet.

**Comment by subsoap** [comment] 2017-12-04 02:39
@chaosddp could you try that?

Another option is using GLFW functions directly https://github.com/subsoap/defos/issues/36

We've been warned to not use GLFW functions because they might remove them at any point but our main goal should be to make these features work so people can publish games and adapt over time if necessary.

**Comment by dapetcu21** [comment] 2018-01-03 20:31
Oh. I haven't tested for that behavior on Windows. On macOS that's how it works because I added a tracking rectangle on the NSView, not the NSWindow, so the title bar should be considered outside the window.

I found this: 
https://stackoverflow.com/questions/5629613/hide-cursor-in-client-rectangle-but-not-on-title-bar

Maybe changing the Windows code to use this instead of / in tandem with WM_LEAVE would help?

**Comment by dapetcu21** [comment] 2018-01-03 20:34
I think I'll give it a go

**Comment by dapetcu21** [comment] 2018-01-03 20:57
I booted up into Windows and apparently it's all fine. WM_MOUSELEAVE correctly only tracks the client area. Also tested hiding the mouse `on_mouse_enter` and showing it `on_mouse_leave` and it works beautifully on both Windows and macOS, allowing you to resize. I guess I'll close this, then.

**Closed by dapetcu21** 2018-01-03 20:57 UTC
